version: '3'
services:
  postgres:
    container_name: mnl_postgres
    image: postgres:9.6.6-alpine
    restart: always
    env_file: env/dev.env
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432'

  django:
    container_name: mnl_django
    build: ./django
    restart: always
    links:
      - postgres
    volumes:
      - ./django:/srv
      - django_static_vol:/srv/static
    env_file: env/dev.env

  nginx:
    container_name: mnl_nginx
    build: ./nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    links:
      - django
    volumes:
      - ./nginx/try_files:/www/data
      - django_static_vol:/var/www/static

volumes:
  django_static_vol:
