# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    working_directory: ~/mnl-api

    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
        - SECRET_KEY: circle_secret_key
        - POSTGRES_HOST: 127.0.0.1
        - POSTGRES_PORT: 5432
        - POSTGRES_DB: circle_db
        - POSTGRES_USER: root

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6-alpine
        environment:
        - POSTGRES_USER: root
        - POSTGRES_DB: circle_db

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "django/requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r django/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "django/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python django/manage.py test django

      - store_artifacts:
          path: test-reports
          destination: test-reports
  test:
    working_directory: ~/mnl-api

    docker:
      - image: circleci/python:3.6.1
        environment:
        - SECRET_KEY: circle_secret_key
        - POSTGRES_HOST: 127.0.0.1
        - POSTGRES_PORT: 5432
        - POSTGRES_DB: circle_db
        - POSTGRES_USER: root

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python django/manage.py test django

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    working_directory: ~/mnl-api
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy mnl-api
workflows:
  version: 2
  build_test_and_approved_deploy:
    jobs:
      - build
      - test
          requires:
            - build
      - hold:
          type: approval
          requires:
           - test
      - deploy:
          requires:
            - hold